config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'usuarios#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # Relaciones
  belongs_to :usuario

  # Validaciones
  validates :titulo, :contenido, presence: true
  validates :titulo, length: { maximum: 30 }
  validates :contenido, presence: true

  # Scopes
  # A scope that gives the posts of the last 5 days
  scope :hace_5_dias, -> { where('created_at >= ?', 5.days.ago) && order(created_at: :desc) }

  scope :recientes, -> { order(created_at: :desc).limit(3) }

  scope :not_millenials, -> { where.not(usuario_id: Usuario.millenials) }

  scope :premiums_millenials, -> { where(usuario_id: Usuario.millenials && Usuario.premiums) }
end

app/models/usuario.rb
# frozen_string_literal: true

class Usuario < ApplicationRecord
  # Relaciones
  has_many :posts

  enum roles: %i[admin premium regular]

  # Validaciones
  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :email, presence: true, uniqueness: true
  validates :nacimiento, presence: true
  validates :roles, presence: true

  # Scopes
  scope :centennials, -> { where(nacimiento: Date.new(1994)..Date.new(2010)) }
  scope :millenials, ->  { where(nacimiento: Date.new(1981)..Date.new(1993)) }
  scope :xgeneration, -> { where(nacimiento: Date.new(1970)..Date.new(1980)) }
  scope :boomers, ->     { where(nacimiento: Date.new(1949)..Date.new(1969)) }
  scope :premiums, -> { where(roles: 'premium') }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:titulo, :contenido, :usuario_id)
  end
end

app/controllers/usuarios_controller.rb
# frozen_string_literal: true

class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[show edit update destroy]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: 'Usuario creado correctamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])
    @usuario.update(usuario_params)
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: 'Usuario actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario destruido.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def usuario_params
    params.require(:usuario).permit(:nombre, :apellido, :email, :nacimiento, :roles)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/usuarios_helper.rb
# frozen_string_literal: true

module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejercicio1Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :titulo %>
  <%= form.text_field :titulo %>

  <%= form.label :contenido %>
  <%= form.text_field :contenido %>

  <%= form.label :usuario %>
  <%= form.select :usuario_id, Usuario.all.map { |u| [u.nombre, u.id]},selected: 0%>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Mostrar este post", @post %> |
  <%= link_to "Volver a posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= post.titulo%>
      <%= link_to "Mostrar este post", post %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Volver a posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= @post.titulo.concat(': ').concat(@post.contenido)%>
  <%= link_to "Editar este post", edit_post_path(@post) %> |
  <%= link_to "Volver a posts", posts_path %>

  <%= button_to "Destruir este post", @post, method: :delete %>
</div>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.label :nombre %><br>
  <%= form.text_field :nombre %><br>

  <%= form.label :apellido %><br>
  <%= form.text_field :apellido %><br>

  <%= form.label :email %><br>
  <%= form.text_field :email %><br>

  <%= form.label :nacimiento %><br>
  <%= form.date_field :nacimiento %><br>

  <%= form.label :Rol %><br>
  <%= form.select :roles, ['admin', 'premium' ,'regular' ], selected: 'regular' %><br>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
    

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Mostrar este usuario", @usuario %> |
  <%= link_to "Volver", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= usuario.nombre.concat(' ').concat(usuario.apellido)%> |
      <%= link_to "Mostrar usuario", usuario %>
      
    </p>
  <% end %>
</div>

<%= link_to "Nuevo usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Volver", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= @usuario.nombre.concat(' ').concat(@usuario.apellido)%> |
  <%= @usuario.email.concat(' ').concat(@usuario.roles.to_s)%> |
  <%= link_to "Editar este usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Volver", usuarios_path %>
  <%= button_to "Destruir este usuario", @usuario, method: :delete %>
</div>